server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reservation
          uri: http://localhost:8072
          predicates:
            - Path=/reservations/**, 
        - id: notification
          uri: http://localhost:8073
          predicates:
            - Path=/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: resume
          uri: http://localhost:8082
          predicates:
            - Path=/resumes/**, 
        - id: interview
          uri: http://localhost:8083
          predicates:
            - Path=/interviews/**, 
        - id: user
          uri: http://localhost:8084
          predicates:
            - Path=/users/**, 
        - id: report
          uri: http://localhost:8085
          predicates:
            - Path=/applicationAnalyzeData/**, /passedReports/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "X-Total-Count"
              - "Link"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: resume
          uri: http://resume:8080
          predicates:
            - Path=/resumes/**, 
        - id: interview
          uri: http://interview:8080
          predicates:
            - Path=/interviews/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: report
          uri: http://report:8080
          predicates:
            - Path=/applicationAnalyzeData/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
